apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: microservices
build:
  local:
    push: false
  artifacts:
  - image: halcika/auth
    context: .
    docker:
      dockerfile: services/auth/dockerfile
  - image: halcika/client
    context: .
    docker:
      dockerfile: services/client/dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/*
