apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: microservices
build:
  local:
    push: false
  artifacts:
    - image: halcika/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: halcika/tickets
      context: tickets
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: halcika/orders
      context: orders
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: halcika/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "**/*.{ts,js}"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
