apiVersion: v1
kind: Secret
metadata:
  name: cookie
type: Opaque
data:
  cookie_path: L2FwaS91c2Vycy92MS9yZWZyZXNo
  cookie_refresh_name: YWlkdWhpdXNhaGRpdWhhaXVzZGhpYXVzaGRodWlhaHM=
  cookie_access_name: aW5zbmRzb25tb3Nva3Nqb2pkb3Nqb2lqam9zaWpvaWpkc29pam9pZGo=
