FROM node:alpine

WORKDIR /app

COPY package.docker.json package.json
COPY yarn.lock .
COPY tsconfig.json .
COPY ./services/client ./services/client

RUN yarn

RUN yarn build

#stage 2
FROM node:alpine

WORKDIR /app

COPY package.docker.json package.json

COPY --from=0 /app/services/client ./services/client

RUN yarn install --production

CMD ["yarn", "--cwd", "services/client", "start"]
